# Generated by Django 3.2.7 on 2021-09-12 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('mobile', models.CharField(max_length=30)),
                ('landline', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('fax', models.CharField(max_length=30)),
                ('ownerId', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('hashedpassword', models.CharField(max_length=300)),
                ('ownerId', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownerId', models.BigIntegerField()),
                ('token', models.CharField(max_length=200)),
                ('time', models.BigIntegerField()),
            ],
        ),
    ]
